server:
  port: 0

spring:
  application:
    name: book-service

  config:
    import: classpath:application-resilience4j.yml

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

      cluster:
        nodes: ${REDIS_CLUSTER_NODES}

  cloud:
    config:
      server:
        bootstrap: true

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans,busrefresh

logging:
  level:
    root: info