spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mybrary-testdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  cloud:
    config:
      enabled: false

kakao:
  api:
    key: ${KAKAO_API_KEY}

aladin:
  api:
    key: ${ALADIN_API_KEY}

eureka:
  client:
    enabled: false

logging:
  level:
    root: debug
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
