name: 'SonarCloud'

on:
  push:
    branches:
      - master
    paths:
      - 'book-service/**'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
    paths:
      - 'book-service/**'

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Setup Application Test Yaml
        uses: microsoft/variable-substitution@v1
        with:
          files: book-service/src/main/resources/application-test.yml
        env:
          aladin.api.key : ${{ secrets.ALADIN_API_KEY }}
          kakao.api.key : ${{ secrets.KAKAO_API_KEY }}

      - name: Setup Bootstrap Yaml
        uses: microsoft/variable-substitution@v1
        with:
          files: book-service/src/main/resources/bootstrap.yml
        env:
          spring.profiles.active: test

      - name: analyze test coverage
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          title: Test Coverage Report
          paths: book-service/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.PR_ACCESS_KEY }}
          min-coverage-overall: 50
          min-coverage-changed-files: 50
          
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and analyze
        working-directory: book-service
        env:
          GITHUB_TOKEN: ${{ secrets.PR_ACCESS_KEY }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonar --info